export const INDUSTRY_TECHNOLOGY = 'INDUSTRY_TECHNOLOGY';
export const INDUSTRY_SOFTWARE = 'INDUSTRY_SOFTWARE';
export const INDUSTRY_ECOMMERCE = 'INDUSTRY_ECOMMERCE';
export const INDUSTRY_FINANCE = 'INDUSTRY_FINANCE';
export const INDUSTRY_BANKING = 'INDUSTRY_BANKING';
export const INDUSTRY_INSURANCE = 'INDUSTRY_INSURANCE';
export const INDUSTRY_HEALTHCARE = 'INDUSTRY_HEALTHCARE';
export const INDUSTRY_EDUCATION = 'INDUSTRY_EDUCATION';
export const INDUSTRY_REAL_ESTATE = 'INDUSTRY_REAL_ESTATE';
export const INDUSTRY_CONSTRUCTION = 'INDUSTRY_CONSTRUCTION';
export const INDUSTRY_MANUFACTURING = 'INDUSTRY_MANUFACTURING';
export const INDUSTRY_LOGISTICS = 'INDUSTRY_LOGISTICS';
export const INDUSTRY_TRANSPORTATION = 'INDUSTRY_TRANSPORTATION';
export const INDUSTRY_RETAIL = 'INDUSTRY_RETAIL';
export const INDUSTRY_HOSPITALITY = 'INDUSTRY_HOSPITALITY';
export const INDUSTRY_TOURISM = 'INDUSTRY_TOURISM';
export const INDUSTRY_FOOD_AND_BEVERAGE = 'INDUSTRY_FOOD_AND_BEVERAGE';
export const INDUSTRY_AGRICULTURE = 'INDUSTRY_AGRICULTURE';
export const INDUSTRY_ENERGY = 'INDUSTRY_ENERGY';
export const INDUSTRY_TELECOMMUNICATIONS = 'INDUSTRY_TELECOMMUNICATIONS';
export const INDUSTRY_MARKETING = 'INDUSTRY_MARKETING';
export const INDUSTRY_ADVERTISING = 'INDUSTRY_ADVERTISING';
export const INDUSTRY_MEDIA = 'INDUSTRY_MEDIA';
export const INDUSTRY_ENTERTAINMENT = 'INDUSTRY_ENTERTAINMENT';
export const INDUSTRY_LEGAL = 'INDUSTRY_LEGAL';
export const INDUSTRY_CONSULTING = 'INDUSTRY_CONSULTING';
export const INDUSTRY_GOVERNMENT = 'INDUSTRY_GOVERNMENT';
export const INDUSTRY_NONPROFIT = 'INDUSTRY_NONPROFIT';
export const INDUSTRY_SPORTS = 'INDUSTRY_SPORTS';
export const INDUSTRY_FASHION = 'INDUSTRY_FASHION';
export const INDUSTRY_AUTOMOTIVE = 'INDUSTRY_AUTOMOTIVE';
export const INDUSTRY_AEROSPACE = 'INDUSTRY_AEROSPACE';
export const INDUSTRY_PHARMACEUTICALS = 'INDUSTRY_PHARMACEUTICALS';
export const INDUSTRY_BIOTECHNOLOGY = 'INDUSTRY_BIOTECHNOLOGY';
export const INDUSTRY_CYBERSECURITY = 'INDUSTRY_CYBERSECURITY';
export const INDUSTRY_DATA_ANALYTICS = 'INDUSTRY_DATA_ANALYTICS';
export const INDUSTRY_ARTIFICIAL_INTELLIGENCE =
	'INDUSTRY_ARTIFICIAL_INTELLIGENCE';
export const INDUSTRY_BLOCKCHAIN = 'INDUSTRY_BLOCKCHAIN';
export const INDUSTRY_GAMING = 'INDUSTRY_GAMING';
export const INDUSTRY_OTHER = 'INDUSTRY_OTHER';

export type ClientIndustry =
	| typeof INDUSTRY_TECHNOLOGY
	| typeof INDUSTRY_SOFTWARE
	| typeof INDUSTRY_ECOMMERCE
	| typeof INDUSTRY_FINANCE
	| typeof INDUSTRY_BANKING
	| typeof INDUSTRY_INSURANCE
	| typeof INDUSTRY_HEALTHCARE
	| typeof INDUSTRY_EDUCATION
	| typeof INDUSTRY_REAL_ESTATE
	| typeof INDUSTRY_CONSTRUCTION
	| typeof INDUSTRY_MANUFACTURING
	| typeof INDUSTRY_LOGISTICS
	| typeof INDUSTRY_TRANSPORTATION
	| typeof INDUSTRY_RETAIL
	| typeof INDUSTRY_HOSPITALITY
	| typeof INDUSTRY_TOURISM
	| typeof INDUSTRY_FOOD_AND_BEVERAGE
	| typeof INDUSTRY_AGRICULTURE
	| typeof INDUSTRY_ENERGY
	| typeof INDUSTRY_TELECOMMUNICATIONS
	| typeof INDUSTRY_MARKETING
	| typeof INDUSTRY_ADVERTISING
	| typeof INDUSTRY_MEDIA
	| typeof INDUSTRY_ENTERTAINMENT
	| typeof INDUSTRY_LEGAL
	| typeof INDUSTRY_CONSULTING
	| typeof INDUSTRY_GOVERNMENT
	| typeof INDUSTRY_NONPROFIT
	| typeof INDUSTRY_SPORTS
	| typeof INDUSTRY_FASHION
	| typeof INDUSTRY_AUTOMOTIVE
	| typeof INDUSTRY_AEROSPACE
	| typeof INDUSTRY_PHARMACEUTICALS
	| typeof INDUSTRY_BIOTECHNOLOGY
	| typeof INDUSTRY_CYBERSECURITY
	| typeof INDUSTRY_DATA_ANALYTICS
	| typeof INDUSTRY_ARTIFICIAL_INTELLIGENCE
	| typeof INDUSTRY_BLOCKCHAIN
	| typeof INDUSTRY_GAMING
	| typeof INDUSTRY_OTHER;

export const CLIENT_INDUSTRY_ARRAY: ClientIndustry[] = [
	INDUSTRY_TECHNOLOGY,
	INDUSTRY_SOFTWARE,
	INDUSTRY_ECOMMERCE,
	INDUSTRY_FINANCE,
	INDUSTRY_BANKING,
	INDUSTRY_INSURANCE,
	INDUSTRY_HEALTHCARE,
	INDUSTRY_EDUCATION,
	INDUSTRY_REAL_ESTATE,
	INDUSTRY_CONSTRUCTION,
	INDUSTRY_MANUFACTURING,
	INDUSTRY_LOGISTICS,
	INDUSTRY_TRANSPORTATION,
	INDUSTRY_RETAIL,
	INDUSTRY_HOSPITALITY,
	INDUSTRY_TOURISM,
	INDUSTRY_FOOD_AND_BEVERAGE,
	INDUSTRY_AGRICULTURE,
	INDUSTRY_ENERGY,
	INDUSTRY_TELECOMMUNICATIONS,
	INDUSTRY_MARKETING,
	INDUSTRY_ADVERTISING,
	INDUSTRY_MEDIA,
	INDUSTRY_ENTERTAINMENT,
	INDUSTRY_LEGAL,
	INDUSTRY_CONSULTING,
	INDUSTRY_GOVERNMENT,
	INDUSTRY_NONPROFIT,
	INDUSTRY_SPORTS,
	INDUSTRY_FASHION,
	INDUSTRY_AUTOMOTIVE,
	INDUSTRY_AEROSPACE,
	INDUSTRY_PHARMACEUTICALS,
	INDUSTRY_BIOTECHNOLOGY,
	INDUSTRY_CYBERSECURITY,
	INDUSTRY_DATA_ANALYTICS,
	INDUSTRY_ARTIFICIAL_INTELLIGENCE,
	INDUSTRY_BLOCKCHAIN,
	INDUSTRY_GAMING,
	INDUSTRY_OTHER,
];
