export const INDUSTRY_TECHNOLOGY = 'technology';
export const INDUSTRY_SOFTWARE = 'software';
export const INDUSTRY_ECOMMERCE = 'ecommerce';
export const INDUSTRY_FINANCE = 'finance';
export const INDUSTRY_BANKING = 'banking';
export const INDUSTRY_INSURANCE = 'insurance';
export const INDUSTRY_HEALTHCARE = 'healthcare';
export const INDUSTRY_EDUCATION = 'education';
export const INDUSTRY_REAL_ESTATE = 'realEstate';
export const INDUSTRY_CONSTRUCTION = 'construction';
export const INDUSTRY_MANUFACTURING = 'manufacturing';
export const INDUSTRY_LOGISTICS = 'logistics';
export const INDUSTRY_TRANSPORTATION = 'transportation';
export const INDUSTRY_RETAIL = 'retail';
export const INDUSTRY_HOSPITALITY = 'hospitality';
export const INDUSTRY_TOURISM = 'tourism';
export const INDUSTRY_FOOD_AND_BEVERAGE = 'foodAndBeverage';
export const INDUSTRY_AGRICULTURE = 'agriculture';
export const INDUSTRY_ENERGY = 'energy';
export const INDUSTRY_TELECOMMUNICATIONS = 'telecommunications';
export const INDUSTRY_MARKETING = 'marketing';
export const INDUSTRY_ADVERTISING = 'advertising';
export const INDUSTRY_MEDIA = 'media';
export const INDUSTRY_ENTERTAINMENT = 'entertainment';
export const INDUSTRY_LEGAL = 'legal';
export const INDUSTRY_CONSULTING = 'consulting';
export const INDUSTRY_GOVERNMENT = 'government';
export const INDUSTRY_NONPROFIT = 'nonprofit';
export const INDUSTRY_SPORTS = 'sports';
export const INDUSTRY_FASHION = 'fashion';
export const INDUSTRY_AUTOMOTIVE = 'automotive';
export const INDUSTRY_AEROSPACE = 'aerospace';
export const INDUSTRY_PHARMACEUTICALS = 'pharmaceuticals';
export const INDUSTRY_BIOTECHNOLOGY = 'biotechnology';
export const INDUSTRY_CYBERSECURITY = 'cybersecurity';
export const INDUSTRY_DATA_ANALYTICS = 'dataAnalytics';
export const INDUSTRY_ARTIFICIAL_INTELLIGENCE = 'artificialIntelligence';
export const INDUSTRY_BLOCKCHAIN = 'blockchain';
export const INDUSTRY_GAMING = 'gaming';
export const INDUSTRY_OTHER = 'other';

export type ClientIndustry =
	| typeof INDUSTRY_TECHNOLOGY
	| typeof INDUSTRY_SOFTWARE
	| typeof INDUSTRY_ECOMMERCE
	| typeof INDUSTRY_FINANCE
	| typeof INDUSTRY_BANKING
	| typeof INDUSTRY_INSURANCE
	| typeof INDUSTRY_HEALTHCARE
	| typeof INDUSTRY_EDUCATION
	| typeof INDUSTRY_REAL_ESTATE
	| typeof INDUSTRY_CONSTRUCTION
	| typeof INDUSTRY_MANUFACTURING
	| typeof INDUSTRY_LOGISTICS
	| typeof INDUSTRY_TRANSPORTATION
	| typeof INDUSTRY_RETAIL
	| typeof INDUSTRY_HOSPITALITY
	| typeof INDUSTRY_TOURISM
	| typeof INDUSTRY_FOOD_AND_BEVERAGE
	| typeof INDUSTRY_AGRICULTURE
	| typeof INDUSTRY_ENERGY
	| typeof INDUSTRY_TELECOMMUNICATIONS
	| typeof INDUSTRY_MARKETING
	| typeof INDUSTRY_ADVERTISING
	| typeof INDUSTRY_MEDIA
	| typeof INDUSTRY_ENTERTAINMENT
	| typeof INDUSTRY_LEGAL
	| typeof INDUSTRY_CONSULTING
	| typeof INDUSTRY_GOVERNMENT
	| typeof INDUSTRY_NONPROFIT
	| typeof INDUSTRY_SPORTS
	| typeof INDUSTRY_FASHION
	| typeof INDUSTRY_AUTOMOTIVE
	| typeof INDUSTRY_AEROSPACE
	| typeof INDUSTRY_PHARMACEUTICALS
	| typeof INDUSTRY_BIOTECHNOLOGY
	| typeof INDUSTRY_CYBERSECURITY
	| typeof INDUSTRY_DATA_ANALYTICS
	| typeof INDUSTRY_ARTIFICIAL_INTELLIGENCE
	| typeof INDUSTRY_BLOCKCHAIN
	| typeof INDUSTRY_GAMING
	| typeof INDUSTRY_OTHER;

export const CLIENT_INDUSTRY_ARRAY: ClientIndustry[] = [
	INDUSTRY_TECHNOLOGY,
	INDUSTRY_SOFTWARE,
	INDUSTRY_ECOMMERCE,
	INDUSTRY_FINANCE,
	INDUSTRY_BANKING,
	INDUSTRY_INSURANCE,
	INDUSTRY_HEALTHCARE,
	INDUSTRY_EDUCATION,
	INDUSTRY_REAL_ESTATE,
	INDUSTRY_CONSTRUCTION,
	INDUSTRY_MANUFACTURING,
	INDUSTRY_LOGISTICS,
	INDUSTRY_TRANSPORTATION,
	INDUSTRY_RETAIL,
	INDUSTRY_HOSPITALITY,
	INDUSTRY_TOURISM,
	INDUSTRY_FOOD_AND_BEVERAGE,
	INDUSTRY_AGRICULTURE,
	INDUSTRY_ENERGY,
	INDUSTRY_TELECOMMUNICATIONS,
	INDUSTRY_MARKETING,
	INDUSTRY_ADVERTISING,
	INDUSTRY_MEDIA,
	INDUSTRY_ENTERTAINMENT,
	INDUSTRY_LEGAL,
	INDUSTRY_CONSULTING,
	INDUSTRY_GOVERNMENT,
	INDUSTRY_NONPROFIT,
	INDUSTRY_SPORTS,
	INDUSTRY_FASHION,
	INDUSTRY_AUTOMOTIVE,
	INDUSTRY_AEROSPACE,
	INDUSTRY_PHARMACEUTICALS,
	INDUSTRY_BIOTECHNOLOGY,
	INDUSTRY_CYBERSECURITY,
	INDUSTRY_DATA_ANALYTICS,
	INDUSTRY_ARTIFICIAL_INTELLIGENCE,
	INDUSTRY_BLOCKCHAIN,
	INDUSTRY_GAMING,
	INDUSTRY_OTHER,
];
