export const AUDIT_ACTIONS = {
	AUTH_LOGIN: 'auth:login',
	AUTH_LOGOUT: 'auth:logout',
	AUTH_PASSWORD_CHANGED: 'auth:password_changed',
	AUTH_PASSWORD_RESET: 'auth:password_reset',
	AUTH_EMAIL_VERIFIED: 'auth:email_verified',
	USERS_CREATED: 'users:created',
	USERS_UPDATED: 'users:updated',
	USERS_DELETED: 'users:deleted',
	SUBSCRIBERS_CREATED: 'subscribers:created',
	SUBSCRIBERS_UPDATED: 'subscribers:updated',
	SUBSCRIBERS_DELETED: 'subscribers:deleted',
	STORAGE_UPLOADED: 'storage:uploaded',
	STORAGE_SOFT_DELETED: 'storage:soft_deleted',
	STORAGE_PERMANENTLY_DELETED: 'storage:permanently_deleted',
	USERS_SOFT_DELETED: 'users:soft_deleted',
	USER_GROUPS_SOFT_DELETED: 'user-groups:soft_deleted',
	USER_GROUPS_CREATED: 'user-groups:created',
	USER_GROUPS_UPDATED: 'user-groups:updated',
	USER_GROUPS_DELETED: 'user-groups:deleted',
	USER_GROUPS_MEMBERS_ADDED: 'user-groups:members_added',
	USER_GROUPS_MEMBER_REMOVED: 'user-groups:member_removed',
	USER_GROUPS_MEMBERS_REMOVED: 'user-groups:members_removed',
	CLIENTS_CREATED: 'clients:created',
	CLIENTS_UPDATED: 'clients:updated',
	CLIENTS_SOFT_DELETED: 'clients:soft_deleted',
	CLIENTS_PERMANENTLY_DELETED: 'clients:permanently_deleted',
	SERVICES_CREATED: 'services:created',
	SERVICES_UPDATED: 'services:updated',
	SERVICES_SOFT_DELETED: 'services:soft_deleted',
	SERVICES_PERMANENTLY_DELETED: 'services:permanently_deleted',
	PORTFOLIO_CREATED: 'portfolio:created',
	PORTFOLIO_UPDATED: 'portfolio:updated',
	PORTFOLIO_SOFT_DELETED: 'portfolio:soft_deleted',
	PORTFOLIO_PERMANENTLY_DELETED: 'portfolio:permanently_deleted',

	PAGES_CREATED: 'pages:created',
	PAGES_UPDATED: 'pages:updated',
	PAGES_SOFT_DELETED: 'pages:soft_deleted',
	PAGES_PERMANENTLY_DELETED: 'pages:permanently_deleted',

	USERS_RESTORED: 'users:restored',
	USER_GROUPS_RESTORED: 'user-groups:restored',
	SUBSCRIBERS_RESTORED: 'subscribers:restored',
	STORAGE_RESTORED: 'storage:restored',
	CLIENTS_RESTORED: 'clients:restored',
	SERVICES_RESTORED: 'services:restored',
	PORTFOLIO_RESTORED: 'portfolio:restored',
	PAGES_RESTORED: 'pages:restored',

	COLLABORATOR_CREATED: 'collaborators:created',
	COLLABORATOR_UPDATED: 'collaborators:updated',
	COLLABORATOR_SOFT_DELETED: 'collaborators:soft_deleted',
	COLLABORATOR_PERMANENTLY_DELETED: 'collaborators:permanently_deleted',
	COLLABORATOR_RESTORED: 'collaborators:restored',

	USERS_BULK_SOFT_DELETED: 'users:bulk_soft_deleted',
	USERS_BULK_RESTORED: 'users:bulk_restored',
	USERS_BULK_PERMANENTLY_DELETED: 'users:bulk_permanently_deleted',

	USER_GROUPS_BULK_SOFT_DELETED: 'user-groups:bulk_soft_deleted',
	USER_GROUPS_BULK_RESTORED: 'user-groups:bulk_restored',
	USER_GROUPS_BULK_PERMANENTLY_DELETED: 'user-groups:bulk_permanently_deleted',

	CLIENTS_BULK_SOFT_DELETED: 'clients:bulk_soft_deleted',
	CLIENTS_BULK_RESTORED: 'clients:bulk_restored',
	CLIENTS_BULK_PERMANENTLY_DELETED: 'clients:bulk_permanently_deleted',

	COLLABORATORS_BULK_SOFT_DELETED: 'collaborators:bulk_soft_deleted',
	COLLABORATORS_BULK_RESTORED: 'collaborators:bulk_restored',
	COLLABORATORS_BULK_PERMANENTLY_DELETED:
		'collaborators:bulk_permanently_deleted',

	SERVICES_BULK_SOFT_DELETED: 'services:bulk_soft_deleted',
	SERVICES_BULK_RESTORED: 'services:bulk_restored',
	SERVICES_BULK_PERMANENTLY_DELETED: 'services:bulk_permanently_deleted',

	PORTFOLIO_BULK_SOFT_DELETED: 'portfolio:bulk_soft_deleted',
	PORTFOLIO_BULK_RESTORED: 'portfolio:bulk_restored',
	PORTFOLIO_BULK_PERMANENTLY_DELETED: 'portfolio:bulk_permanently_deleted',

	PAGES_BULK_SOFT_DELETED: 'pages:bulk_soft_deleted',
	PAGES_BULK_RESTORED: 'pages:bulk_restored',
	PAGES_BULK_PERMANENTLY_DELETED: 'pages:bulk_permanently_deleted',

	STORAGE_BULK_SOFT_DELETED: 'storage:bulk_soft_deleted',
	STORAGE_BULK_RESTORED: 'storage:bulk_restored',
	STORAGE_BULK_PERMANENTLY_DELETED: 'storage:bulk_permanently_deleted',

	SUBSCRIBERS_BULK_SOFT_DELETED: 'subscribers:bulk_soft_deleted',
	SUBSCRIBERS_BULK_RESTORED: 'subscribers:bulk_restored',
	SUBSCRIBERS_BULK_PERMANENTLY_DELETED: 'subscribers:bulk_permanently_deleted',

	PAGE_REVISION_RESTORED: 'pages:revision_restored',
	PAGE_SECTIONS_REPLACED: 'pages:sections_replaced',

	SITE_CONFIG_UPDATED: 'site-config:updated',

	CATEGORIES_CREATED: 'categories:created',
	CATEGORIES_UPDATED: 'categories:updated',
	CATEGORIES_SOFT_DELETED: 'categories:soft_deleted',
	CATEGORIES_PERMANENTLY_DELETED: 'categories:permanently_deleted',
	CATEGORIES_RESTORED: 'categories:restored',
	CATEGORIES_BULK_SOFT_DELETED: 'categories:bulk_soft_deleted',
	CATEGORIES_BULK_RESTORED: 'categories:bulk_restored',
	CATEGORIES_BULK_PERMANENTLY_DELETED: 'categories:bulk_permanently_deleted',

	TAGS_CREATED: 'tags:created',
	TAGS_UPDATED: 'tags:updated',
	TAGS_SOFT_DELETED: 'tags:soft_deleted',
	TAGS_PERMANENTLY_DELETED: 'tags:permanently_deleted',
	TAGS_RESTORED: 'tags:restored',
	TAGS_BULK_SOFT_DELETED: 'tags:bulk_soft_deleted',
	TAGS_BULK_RESTORED: 'tags:bulk_restored',
	TAGS_BULK_PERMANENTLY_DELETED: 'tags:bulk_permanently_deleted',
} as const;

export type AuditAction = (typeof AUDIT_ACTIONS)[keyof typeof AUDIT_ACTIONS];
