export const STORAGE_ERRORS = {
	FILE_REQUIRED: 'FILE_REQUIRED',
	FILE_NOT_FOUND: 'STORAGE_FILE_NOT_FOUND',
	FILE_TYPE_NOT_ALLOWED: 'FILE_TYPE_NOT_ALLOWED',
	MIME_TYPE_MISMATCH: 'MIME_TYPE_MISMATCH',
	FILE_SIZE_EXCEEDED: 'FILE_SIZE_EXCEEDED',
	TOO_MANY_FILES: 'TOO_MANY_FILES',
	UPLOAD_FAILED: 'UPLOAD_FAILED',
	DELETE_FAILED: 'DELETE_FAILED',
	DRIVER_NOT_CONFIGURED: 'DRIVER_NOT_CONFIGURED',
} as const;

export type StorageErrorCode =
	(typeof STORAGE_ERRORS)[keyof typeof STORAGE_ERRORS];
